[tool.poetry]
name = "simulation"
version = "0.1.0"
description = ""
authors = ["nszknao"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gymnasium = {extras = ["mujoco","classic-control","other"], version = "0.29.1"}
mujoco = "3.2.3"
torch = "2.5.1"
numpy = "2.1.2"
polars = "1.8.2"
pyarrow = "17.0.0"
altair = "5.4.1"
ipython = "8.27.0"
stable-baselines3 = "^2.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
